#!/usr/bin/python3

#############################################################################
#                                 Profiling                                 #
#############################################################################
# 


import cProfile
from cProfile import Profile
import pstats
import numpy
from numpy import random
import pdb
import sys
import time


# Just an arbitrary example juggling random integer and float arrays generated by numpy
def my_function():
    int_max = -sys.maxsize
    float_max = float('-inf')
    for i in range(1, 5):
        arr = random.randint(100, size=100000) # generate 100000 integers between 0-99
        arr2 = random.rand(100000) # generate 100000 floats between 0-1
        arr.sort()
        arr2.sort()
        int_max = max(arr) if max(arr) > int_max else int_max
        float_max = max(arr2) if max(arr2) > float_max else float_max
        
        # Sleep between 0-1 seconds
        time.sleep(random.randint(2))
    return [int_max, float_max]

    

print(my_function())


if __name__ == '__main__':
    cProfile.run('my_function()')
